In [42]:
import pandas as pd
import numpy as np

In [43]:
import gensim
import os

In [44]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [45]:

story = []
for filename in os.listdir("data"):
    with open(os.path.join("data", filename), encoding="latin-1") as f:
        corpus = f.read()
        raw_sent = sent_tokenize(corpus)
        for sent in raw_sent:
            story.append(simple_preprocess(sent))

In [46]:
story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [47]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4
)

In [48]:
model.build_vocab(story)

In [49]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(6569050, 8628190)

In [50]:
model.wv.most_similar("daenerys")

[('stormborn', 0.8161722421646118),
 ('unburnt', 0.7355679869651794),
 ('targaryen', 0.7292386293411255),
 ('princess', 0.7242856621742249),
 ('queen', 0.7225720882415771),
 ('viserys', 0.6906264424324036),
 ('myrcella', 0.6807527542114258),
 ('dorne', 0.6641805768013),
 ('margaery', 0.6590611934661865),
 ('drogo', 0.6528218984603882)]

In [51]:
model.wv.doesnt_match(["jon","rikon","robb","arya","sansa","bran"])

'jon'

In [52]:
model.wv.doesnt_match(["cersei","jaime","bronn","tyrion"])

'bronn'

In [53]:
model.wv["jon"]

array([-0.5790813 ,  0.02940802,  1.1534714 , -0.24880937, -0.8807104 ,
       -0.1585417 ,  0.9327452 ,  2.4121232 , -0.83789736,  0.7183079 ,
       -0.15853505, -0.284182  ,  0.9103303 , -2.203977  , -0.12285934,
       -0.7764939 ,  0.2995979 ,  3.5097668 ,  0.63946354, -1.4642172 ,
        1.8688937 , -2.6809967 ,  0.66118175,  1.8802675 , -0.31375474,
       -2.4709933 ,  1.2929636 ,  2.5515172 , -0.140029  ,  0.49404714,
       -2.0550494 , -0.6871829 ,  1.0527767 , -1.5530211 , -0.4422133 ,
        0.96565586,  0.9431848 ,  0.17247778,  1.0603089 ,  0.31534764,
       -1.6470222 , -1.8349262 ,  0.501923  ,  1.3500382 ,  0.7473427 ,
       -2.799257  , -0.7427105 ,  1.0920439 , -0.43952325, -0.34978393,
       -0.42505494, -0.8065603 ,  2.119558  , -0.21594536, -0.6529424 ,
        0.3280495 , -1.1531569 , -1.9699517 ,  0.0805358 , -1.5191505 ,
       -0.43785048,  2.4052906 ,  0.87498087, -1.0433394 , -0.58522666,
       -0.30686262,  0.6361637 ,  2.864544  , -0.7325313 ,  0.65

In [54]:
model.wv.similarity("arya", "sansa")

np.float32(0.8457848)

In [55]:
model.wv.similarity("cersei","sansa")

np.float32(0.7769277)

In [56]:
model.wv.similarity("tywin","sansa")

np.float32(0.25504476)

In [57]:
model.wv.get_normed_vectors()

array([[-0.037096  ,  0.04477796,  0.2283654 , ..., -0.13477407,
         0.00871504,  0.07373793],
       [-0.06400883, -0.06213029, -0.00185992, ..., -0.06595382,
         0.00451696,  0.22084782],
       [ 0.14331709, -0.03149031, -0.10998742, ..., -0.01936766,
         0.10573119, -0.10210397],
       ...,
       [ 0.1346998 , -0.09051164, -0.07702453, ...,  0.09362537,
         0.08750124, -0.14542909],
       [ 0.08227255,  0.00619176,  0.00260261, ..., -0.14674735,
         0.08317493, -0.0238243 ],
       [ 0.2123168 , -0.04520953, -0.04622195, ...,  0.06792634,
         0.00067758, -0.14093879]], shape=(17453, 100), dtype=float32)

In [58]:
y=model.wv.index_to_key
len(y)

17453

In [59]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'would',
 'were',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'we',
 'could',
 'are',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'king',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'who',
 'down',
 'well',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'father',
 'old',
 'hand',
 'even',
 'too',
 'tyrion',
 'before',
 'never',
 'an',
 'off',
 'know',
 'see',
 'into',
 'made',
 'now',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'then',
 'how',
 'long',
 'has',
 'can',
 'might',
 'us',
 'come',
 'where',
 'here',
 'through',
 'face',
 'still',
 'head',
 'red',
 'll',
 'way',
 'boy',
 'page',
 'must',
 'once',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 

In [60]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)

In [61]:
X=pca.fit_transform(model.wv.get_normed_vectors())

In [62]:
X[:5]

array([[ 0.13382119,  0.5882544 , -0.0949069 ],
       [ 0.16483039,  0.33442292, -0.00718987],
       [-0.27322477,  0.5966649 ,  0.18751112],
       [ 0.00962361,  0.3419183 , -0.17342478],
       [-0.0816585 ,  0.5631667 ,  0.23059931]], dtype=float32)

In [ ]:
import plotly.express as px
fig=px.scatter_3d(X[200:300],x=0,y=1,z=2,color=y[200:300])
fig.show()